# -*- mode: python ; coding: utf-8 -*-
#
# Build requirements
# - pdf2ps (comes with ghostscript)
# - poster 
#

Import('*')

env.Command('testpage-a4-v.ps', 'testpages-a4.pdf',
            'pdf2ps -dFirstPage=1 -dLastPage=1 $SOURCE $TARGET')
env.Command('testpage-a4-h.ps', 'testpages-a4.pdf',
            'pdf2ps -dFirstPage=2 -dLastPage=2 $SOURCE $TARGET')

for mediasize in ('a4', 'a3'):
    for postersize in ('a3',):
        for orientation in ('h', 'v'):
            env.Command('poster-%s-%s-on-%s.ps' % (orientation, postersize, mediasize),
                        'testpage-a4-%s.ps' % orientation,
                        'poster -m %s -p %s $SOURCE -o $TARGET' % (mediasize, postersize))

env.Command('chessboard.pdf', 'gen-chessboard.py',
            'python $SOURCE $TARGET')
env.Command('chessboard.ps', 'chessboard.pdf',
            'pdf2ps -dFirstPage=1 -dLastPage=1 $SOURCE $TARGET')
env.Command('chessboard-poster.ps', 'chessboard.ps',
            'poster -vv -m 21x29+5,10cm $SOURCE -o $TARGET')

env.Command(['allboxes-noboxes.pdf', 'allboxes.pdf'],
            'gen-allboxespage.py',
            'python $SOURCE $TARGETS')
